[package]
name = "ytsaurus-examples"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Example YTsaurus worker binaries built on ytsaurus-job"
publish = false

[dependencies]
ytsaurus-job.workspace = true
ytsaurus-yson.workspace = true
serde.workspace = true
serde_bytes.workspace = true
